# Generated by Django 4.1.1 on 2022-09-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=20)),
                ('by', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('decendants', models.IntegerField(default=0)),
                ('url', models.CharField(default='http://stoplight.io/prism/', max_length=120)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='decendant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsList.item')),
            ],
        ),
    ]
