# Generated by Django 4.1.1 on 2022-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0002_alter_item_decendants_alter_item_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
