# Generated by Django 4.1.1 on 2022-09-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0003_alter_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dead',
            field=models.BooleanField(default=False),
        ),
    ]
