# Generated by Django 4.1.1 on 2022-09-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0004_item_dead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='decendants',
            new_name='descendants',
        ),
    ]
