# Generated by Django 4.1.1 on 2022-09-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0006_decendant_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsList.item'),
        ),
        migrations.DeleteModel(
            name='decendant',
        ),
    ]
