# Generated by Django 4.1.1 on 2022-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0007_item_parent_delete_decendant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dead',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
