# Generated by Django 4.1.1 on 2022-09-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0010_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
    ]
