# Generated by Django 4.1.1 on 2022-09-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0011_remove_item_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
