# Generated by Django 4.1.1 on 2022-09-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0012_item_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fetches',
            field=models.BooleanField(default=False),
        ),
    ]
