# Generated by Django 4.1.1 on 2022-09-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0013_item_fetches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fetches',
            new_name='fetched',
        ),
    ]
