# Generated by Django 4.1.1 on 2022-09-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0017_customitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomItem',
        ),
    ]
