# Generated by Django 4.1.1 on 2022-09-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsList', '0018_delete_customitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
